In [1]:
import tensorflow as tf

In [2]:
print(f"wersja tf: {tf.__version__}")

wersja tf: 2.10.1


In [3]:
#ładowanie zbioru danych
mnist = tf.keras.datasets.mnist

(x_train,y_train),(x_test,y_test) = mnist.load_data()
#normalizacja danych
x_train,x_test = x_train/255.0,x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
#model sieci neuronowej
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
print(predictions)

[[-0.06399503 -0.31783062 -0.6760609  -0.17125538 -0.1895721   0.29244852
  -0.28305894 -0.27851158  0.5495722   0.65781724]]


In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.0905638 , 0.07026114, 0.04910637, 0.08135272, 0.07987616,
 0.12934692, 0.07274722, 0.07307878, 0.1672721 , 0.18639477]],
 dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3019 - accuracy: 0.9118
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1428 - accuracy: 0.9574
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1089 - accuracy: 0.9664
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0882 - accuracy: 0.9722
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0770 - accuracy: 0.9758


In [11]:
#ocena modelu
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0757 - accuracy: 0.9768 - 556ms/epoch - 2ms/step


[0.07565972954034805, 0.9768000245094299]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.2099812e-07, 1.8772743e-09, 2.2071811e-06, 1.3847824e-04,
        2.3036547e-12, 6.1294645e-09, 1.6265882e-14, 9.9985862e-01,
        8.4554962e-08, 4.3797834e-07],
       [1.3069904e-08, 2.1578873e-05, 9.9996996e-01, 8.0045475e-06,
        1.2731105e-15, 2.6604556e-07, 5.0255076e-09, 2.0986624e-13,
        1.9733227e-07, 5.8246410e-14],
       [8.0372325e-07, 9.9789375e-01, 1.8159454e-04, 1.0222768e-05,
        9.2665345e-05, 8.1018115e-06, 6.7931874e-06, 1.5481053e-03,
        2.5416358e-04, 3.8055118e-06],
       [9.9980730e-01, 5.3288701e-08, 9.6836273e-05, 2.6602712e-07,
        8.3072729e-07, 8.6777109e-06, 4.1725605e-07, 3.2602195e-05,
        2.5474250e-08, 5.2989282e-05],
       [8.0826402e-07, 9.7910906e-09, 8.8037626e-07, 1.3515095e-08,
        9.9870622e-01, 3.5045278e-07, 2.0520834e-07, 1.6960056e-04,
        1.6998165e-07, 1.1217212e-03]], dtype=float32)>

In [16]:
import numpy as np
w1 = probability_model(x_test[:1])
np.argmax(w1)

7